export const CURRENT_STORE_ACTIONS = {
  FETCH_LIST_ITEMS: 'FETCH_LIST_ITEMS',
  FETCH_STORE_ESSENTIALS: 'FETCH_STORE_ESSENTIALS',
  SET_LIST: 'SET_LIST',
  SET_STORE_ESSENTIALS: 'SET_STORE_ESSENTIALS',
  UPDATE_ITEM: 'UPDATE_ITEM',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  ADD_ITEM: 'ADD_ITEM',
};