export const CURRENT_STORE_ACTIONS = {
  FETCH_LIST_ITEMS: 'FETCH_LIST_ITEMS',
  FETCH_STORE_ESSENTIALS: 'FETCH_STORE_ESSENTIALS',
  SET_LIST: 'SET_LIST',
  SET_STORE_ESSENTIALS: 'SET_STORE_ESSENTIALS',
  COMPLETE_ITEM: 'COMPLETE_ITEM',
  UNCOMPLETE_ITEM: 'UNCOMPLETE_ITEM',
  UPDATE_ITEM_QUANTITY: 'UPDATE_ITEM_QUANTITY',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  ADD_ITEM: 'ADD_ITEM',
  START_ESSENTIALS_EDITING_MODE: 'START_ESSENTIALS_EDITING_MODE',
  STOP_ESSENTIALS_EDITING_MODE: 'STOP_ESSENTIALS_EDITING_MODE',
  START_ITEM_EDITING_MODE: 'START_ITEM_EDITING_MODE',
  STOP_ITEM_EDITING_MODE: 'STOP_ITEM_EDITING_MODE',
  SET_EDITING_ITEM: 'SET_EDITING_ITEM',
  CLEAR_EDITING_ITEM: 'CLEAR_EDITING_ITEM',
  UPDATE_ESSENTIALS_LIST: 'UPDATE_ESSENTIALS_LIST',
  REMOVE_ITEM: 'REMOVE_ITEM',
  START_LIST_EDITING_MODE: 'START_LIST_EDITING_MODE',
  STOP_LIST_EDITING_MODE: 'STOP_LIST_EDITING_MODE',
  START_ITEM_MOVE_MODE: 'START_ITEM_MOVE_MODE',
  STOP_ITEM_MOVE_MODE: 'STOP_ITEM_MOVE_MODE',
  SET_ITEM_MOVE_TARGET_STORE: 'SET_ITEM_MOVE_TARGET_STORE',
  CLEAR_ITEM_MOVE_TARGET_STORE: 'CLEAR_ITEM_MOVE_TARGET_STORE',
  MOVE_SELECTED_ITEMS_TO_TARGET_STORE: 'MOVE_SELECTED_ITEMS_TO_TARGET_STORE',
  START_ITEM_DELETE_MODE: 'START_ITEM_DELETE_MODE',
  STOP_ITEM_DELETE_MODE: 'STOP_ITEM_DELETE_MODE',
  DELETE_SELECTED_ITEMS_FROM_STORE: 'DELETE_SELECTED_ITEMS_FROM_STORE',
  FETCH_STORE_AREAS: 'FETCH_STORE_AREAS',
  SET_STORE_AREAS: 'SET_STORE_AREAS',
  START_AREA_EDITING_MODE: 'START_AREA_EDITING_MODE',
  STOP_AREA_EDITING_MODE: 'STOP_AREA_EDITING_MODE',
  ADD_STORE_AREA: 'ADD_STORE_AREA',
  DELETE_STORE_AREA: 'DELETE_STORE_AREA',
  UPDATE_STORE_AREA_ORDER: 'UPDATE_STORE_AREA_ORDER',
};

export const addItemOrUpdateQuantity = (storeId, itemList, newItem) => {
  const action = {};
  const existingListItem = itemList.find(currentItem => 
    currentItem.item_id === (newItem.item_id || newItem.id) && currentItem.completed === false
  );
  if (existingListItem) {
    action.type = CURRENT_STORE_ACTIONS.UPDATE_ITEM_QUANTITY;
    action.payload = {
      ...existingListItem,
      quantity: existingListItem.quantity + 1
    };
  } else {
    action.type = CURRENT_STORE_ACTIONS.ADD_ITEM;
    action.payload = {
      storeId: storeId,
      item: newItem,
    };
  }
  return action;
};