export const ITEM_SELECT_ACTIONS = {
  START_ITEM_SELECTION_MODE: 'START_ITEM_SELECTION_MODE',
  STOP_ITEM_SELECTION_MODE: 'STOP_ITEM_SELECTION_MODE',
  SET_SELECTED_ITEMS: 'SET_SELECTED_ITEMS',
  ADD_TO_SELECTED_ITEMS: 'ADD_TO_SELECTED_ITEMS',
  REMOVE_FROM_SELECTED_ITEMS: 'REMOVE_FROM_SELECTED_ITEMS',
  CLEAR_SELECTED_ITEMS: 'CLEAR_SELECTED_ITEMS',
};