export const ITEM_ACTIONS = {
  FETCH_ALL_ITEMS: 'FETCH_ALL_ITEMS',
  SET_ALL_ITEMS: 'SET_ALL_ITEMS',
  START_ITEM_SEARCH_MODE: 'START_ITEM_SEARCH_MODE',
  STOP_ITEM_SEARCH_MODE: 'STOP_ITEM_SEARCH_MODE',
  SET_ITEM_SEARCH_TERM: 'SET_ITEM_SEARCH_TERM',
};