export const STORE_ACTIONS = {
  FETCH_USER_STORES: 'FETCH_USER_STORES',
  SET_USER_STORES: 'SET_USER_STORES',
  SET_CURRENT_STORE: 'SET_CURRENT_STORE',
  UPDATE_STORE_NAME: 'UPDATE_STORE_NAME',
  ADD_NEW_STORE: 'ADD_NEW_STORE',
};