export const STYLE_CONSTANTS = {
  MAX_SCREEN_WIDTH: 768 + 10,
  BOTTOM_NAV_HEIGHT: 60,
  TOP_BAR_HEIGHT: 40,
  DESKTOP_VERTICAL_MARGIN: 5, //vh
  CONTENT_MARGIN: 10,
  TILE_SIZE: 118,
  TILE_MARGIN: 3,
  // TOTAL_TILE_WIDTH is its size plus the left and right margins
  TOTAL_TILE_WIDTH: 118 + 3 * 2,
  PRIMARY_GREEN: '#2E8B57',
  LIGHT_GREEN: '#4DB571',
  RED: '#A82D1E',
  ORANGE: '#DB9034',
  BLUE: '#2C8DBE'
};
